// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319024754_AgregarEstadoAInvitado")]
    partial class AgregarEstadoAInvitado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Domain.Entities.Acompañante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InvitadoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvitadoId");

                    b.ToTable("Acompañante");
                });

            modelBuilder.Entity("Domain.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Domain.Entities.IngresosLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvitadoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvitadoId");

                    b.ToTable("IngresosLogs");
                });

            modelBuilder.Entity("Domain.Entities.Invitado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CuposIngresado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("IngresosLogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MesaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPersonas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("MesaId");

                    b.ToTable("Invitados");
                });

            modelBuilder.Entity("Domain.Entities.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadSillas")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaEscaneado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEscaneado")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvitadoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QrUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvitadoId")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Acompañante", b =>
                {
                    b.HasOne("Domain.Entities.Invitado", "Invitado")
                        .WithMany("Acompañantes")
                        .HasForeignKey("InvitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitado");
                });

            modelBuilder.Entity("Domain.Entities.IngresosLog", b =>
                {
                    b.HasOne("Domain.Entities.Invitado", "Invitado")
                        .WithMany("IngresosLogs")
                        .HasForeignKey("InvitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitado");
                });

            modelBuilder.Entity("Domain.Entities.Invitado", b =>
                {
                    b.HasOne("Domain.Entities.Evento", "Evento")
                        .WithMany("Invitados")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Mesa", "Mesa")
                        .WithMany("Invitados")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Evento");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("Domain.Entities.Mesa", b =>
                {
                    b.HasOne("Domain.Entities.Evento", "Eventos")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.Invitado", "Invitado")
                        .WithOne("Ticket")
                        .HasForeignKey("Domain.Entities.Ticket", "InvitadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invitado");
                });

            modelBuilder.Entity("Domain.Entities.Evento", b =>
                {
                    b.Navigation("Invitados");
                });

            modelBuilder.Entity("Domain.Entities.Invitado", b =>
                {
                    b.Navigation("Acompañantes");

                    b.Navigation("IngresosLogs");

                    b.Navigation("Ticket")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Mesa", b =>
                {
                    b.Navigation("Invitados");
                });
#pragma warning restore 612, 618
        }
    }
}
